<a href="https://colab.research.google.com/github/AraceliAR/Ciencia_de_datos/blob/main/Actividad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importar librerías necesarias para el correcto funcionamiento**

In [14]:
#librería Numpy - pandas
import numpy as np
import pandas as pd

**Crea una matriz de 10x10 con valores aleatorios y encuentra los valores mínimo y máximo**

In [4]:
matriz= np.random.randint(50, size=(10, 10))
matriz

array([[32, 36, 19,  1, 14, 34, 41, 22, 20, 41],
       [46, 49,  0, 34, 49, 30,  4, 15, 19,  3],
       [10, 35, 40, 21, 38, 45, 17, 43, 46, 46],
       [29, 25, 34, 45, 22, 17, 23, 27, 43, 25],
       [29, 13, 17, 12, 11, 45, 22, 48, 32, 31],
       [47,  8, 20,  6, 11, 12, 41, 16, 11, 47],
       [44, 42, 19, 21, 37,  3, 23,  3,  5, 27],
       [44, 20, 15, 21, 45, 17, 26, 21, 25, 29],
       [ 1, 16, 31, 42, 13, 10, 10, 27, 44, 45],
       [14, 14, 10,  5, 17,  0, 41, 38,  5, 47]])

In [5]:
#Mín
matriz.min(axis=0)

array([ 1,  8,  0,  1, 11,  0,  4,  3,  5,  3])

In [6]:
matriz.min(axis=1)

array([ 1,  0, 10, 17, 11,  6,  3, 15,  1,  0])

In [7]:
matriz.min()

0

In [8]:
matriz.max()

49

**Crea un vector aleatorio de tamaño 30 y encuentra el valor medio**

In [9]:
vector = np.random.randint(100,size=(30))
vector

array([97, 91,  2,  2, 59, 78, 56, 42, 28,  9, 17,  2, 41, 96, 41, 67, 25,
       79, 45, 14, 67, 99, 80, 70, 71, 49,  2, 95, 91,  2])

In [10]:
vector.mean()

50.56666666666667

**Crea un DataFrame a partir de la siguiente lista:**

In [11]:
(datos = {
    'nombre': ['María', 'Luis', 'Carmen', 'Antonio', 'Sara', 'Pedro', 'Laura', 'Javier', 'Ana', 'Carlos', 'Elena', 'Pablo', 'Isabel', 'Juan', 'Natalia', 'Roberto', 'Lucía', 'Miguel', 'Alicia', 'Francisco'],
    'edad': [18, 22, 20, 21, 25, 30, 28, 23, 29, 26, 24, 27, 32, 31, 35, 33, 40, 38, 36, 39],
    'grado': ['Economía', 'Medicina', 'Arquitectura', 'Economía', 'Psicología', 'Ingeniería', 'Derecho', 'Marketing', 'Biología', 'Informática', 'Periodismo', 'Física', 'Historia', 'Matemáticas', 'Ciencias Políticas', 'Economía', 'Psicología', 'Ingeniería', 'Derecho', 'Marketing'],
    'correo': ['maria@gmail.com', 'luis@yahoo.es', 'carmen@gmail.com', 'antonio@gmail.com', 'sara@gmail.com', 'pedro@yahoo.es', 'laura@gmail.com', 'javier@gmail.com', 'ana@yahoo.es', 'carlos@gmail.com', 'elena@gmail.com', 'pablo@yahoo.es', 'isabel@gmail.com', 'juan@gmail.com', 'natalia@yahoo.es', 'roberto@gmail.com', 'lucia@gmail.com', 'miguel@yahoo.es', 'alicia@gmail.com', 'francisco@gmail.com'],
    'ciudad': ['Madrid', 'Barcelona', 'Sevilla', 'Valencia', 'Zaragoza', 'Málaga', 'Murcia', 'Palma de Mallorca', 'Las Palmas', 'Zaragoza', 'Vigo', 'Gijón', 'Valladolid', 'La Coruña', 'Granada', 'Alicante', 'Bilbao', 'Córdoba', 'Vitoria', 'Santa Cruz de Tenerife'],
    'telefono': ['123-456-789', '987-654-321', '555-123-456', '789-321-654', '111-222-333', '444-555-666', '777-888-999', '222-333-444', '555-666-777', '888-999-000', '111-222-333', '444-555-666', '777-888-999', '222-333-444', '555-666-777', '888-999-000', '111-222-333', '444-555-666', '777-888-999', '222-333-444'],
    'genero': ['Femenino', 'Masculino', 'Femenino', 'Masculino', 'Femenino', 'Masculino', 'Femenino', 'Masculino', 'Femenino', 'Masculino', 'Femenino', 'Masculino', 'Femenino', 'Masculino', 'Femenino', 'Masculino', 'Femenino', 'Masculino', 'Femenino', 'Masculino'],
    'hobbies': ['Leer', 'Deporte', 'Arte', 'Viajar', 'Música', 'Cine', 'Cocina', 'Fotografía', 'Juegos de mesa', 'Senderismo', 'Teatro', 'Bailar', 'Ajedrez', 'Natación', 'Bicicleta', 'Videojuegos', 'Pintura', 'Escalada', 'Jardinería', 'Viajar'],
    'nacionalidad': ['Española', 'Mexicana', 'Española', 'Colombiana', 'Chilena', 'Peruana', 'Argentina', 'Uruguaya', 'Venezolana', 'Ecuatoriana', 'Boliviana', 'Paraguaya', 'Costarricense', 'Guatemalteca', 'Panameña', 'Cubana', 'Dominicana', 'Puertorriqueña', 'Nicaragüense', 'Hondureña'],
    'idioma_principal': ['Español', 'Español', 'Español', 'Español', 'Español', 'Español', 'Español', 'Español', 'Español', 'Español', 'Español', 'Español', 'Español', 'Español', 'Español', 'Español', 'Español', 'Español', 'Español', 'Español'],
    'puntuacion_examen': [85, 92, 78, 88, 95, 86, 90, 78, 88, 92, 80, 94, 87, 89, 96, 82, 91, 93, 84, 97],
    'estado_civil': ['Soltera', 'Soltero', 'Soltera', 'Soltero', 'Casada', 'Soltero', 'Casada', 'Soltero', 'Casada', 'Divorciado', 'Soltera', 'Viudo', 'Casada', 'Soltero', 'Casada', 'Soltero', 'Casada', 'Soltero', 'Casada', 'Soltero'],
    'nivel_educativo': ['Licenciatura', 'Licenciatura', 'Licenciatura', 'Licenciatura', 'Maestría', 'Licenciatura', 'Doctorado', 'Maestría', 'Licenciatura', 'Maestría', 'Licenciatura', 'Doctorado', 'Licenciatura', 'Maestría', 'Licenciatura', 'Doctorado', 'Licenciatura', 'Maestría', 'Doctorado', 'Licenciatura'],
    'altura': [180.43, 184.36, 176.32, 159.25, 170.33, 170.99, 168.37, 150.99, 158.74, 166.55, 170.07, 161.40, 162.12, 175.75, 150.72, 177.87, 187.94, 161.97, 182.92, 183.31],
    'peso': [63.33, 82.26, 56.45, 58.06, 90.22, 84.68, 67.17, 76.52, 97.55, 50.76, 92.71, 98.16, 50.91 , 54.43, 96.54, 62.49, 98.84, 91.99, 75.02, 78.58]
})



In [17]:
tabla= pd.DataFrame(datos)
tabla

nombre  edad               grado               correo  \
0       María    18            Economía      maria@gmail.com   
1        Luis    22            Medicina        luis@yahoo.es   
2      Carmen    20        Arquitectura     carmen@gmail.com   
3     Antonio    21            Economía    antonio@gmail.com   
4        Sara    25          Psicología       sara@gmail.com   
5       Pedro    30          Ingeniería       pedro@yahoo.es   
6       Laura    28             Derecho      laura@gmail.com   
7      Javier    23           Marketing     javier@gmail.com   
8         Ana    29            Biología         ana@yahoo.es   
9      Carlos    26         Informática     carlos@gmail.com   
10      Elena    24          Periodismo      elena@gmail.com   
11      Pablo    27              Física       pablo@yahoo.es   
12     Isabel    32            Historia     isabel@gmail.com   
13       Juan    31         Matemáticas       juan@gmail.com   
14    Natalia    35  Ciencias Políticas     natalia@yahoo.es   
15    Roberto    33            Economía    roberto@gmail.com   
16      Lucía    40          Psicología      lucia@gmail.com   
17     Miguel    38          Ingeniería      miguel@yahoo.es   
18     Alicia    36             Derecho     alicia@gmail.com   
19  Francisco    39           Marketing  francisco@gmail.com   

                    ciudad     telefono     genero         hobbies  \
0                   Madrid  123-456-789   Femenino            Leer   
1                Barcelona  987-654-321  Masculino         Deporte   
2                  Sevilla  555-123-456   Femenino            Arte   
3                 Valencia  789-321-654  Masculino          Viajar   
4                 Zaragoza  111-222-333   Femenino          Música   
5                   Málaga  444-555-666  Masculino            Cine   
6                   Murcia  777-888-999   Femenino          Cocina   
7        Palma de Mallorca  222-333-444  Masculino      Fotografía   
8               Las Palmas  555-666-777   Femenino  Juegos de mesa   
9                 Zaragoza  888-999-000  Masculino      Senderismo   
10                    Vigo  111-222-333   Femenino          Teatro   
11                   Gijón  444-555-666  Masculino          Bailar   
12              Valladolid  777-888-999   Femenino         Ajedrez   
13               La Coruña  222-333-444  Masculino        Natación   
14                 Granada  555-666-777   Femenino       Bicicleta   
15                Alicante  888-999-000  Masculino     Videojuegos   
16                  Bilbao  111-222-333   Femenino         Pintura   
17                 Córdoba  444-555-666  Masculino        Escalada   
18                 Vitoria  777-888-999   Femenino      Jardinería   
19  Santa Cruz de Tenerife  222-333-444  Masculino          Viajar   

      nacionalidad idioma_principal  puntuacion_examen estado_civil  \
0         Española          Español                 85      Soltera   
1         Mexicana          Español                 92      Soltero   
2         Española          Español                 78      Soltera   
3       Colombiana          Español                 88      Soltero   
4          Chilena          Español                 95       Casada   
5          Peruana          Español                 86      Soltero   
6        Argentina          Español                 90       Casada   
7         Uruguaya          Español                 78      Soltero   
8       Venezolana          Español                 88       Casada   
9      Ecuatoriana          Español                 92   Divorciado   
10       Boliviana          Español                 80      Soltera   
11       Paraguaya          Español                 94        Viudo   
12   Costarricense          Español                 87       Casada   
13    Guatemalteca          Español                 89      Soltero   
14        Panameña          Español                 96       Casada   
15          Cubana          Español                 82 

**Despliega las 7 primeras filas del DataFrame**


In [19]:
tabla.head(7)

nombre  edad         grado             correo     ciudad     telefono  \
0    María    18      Economía    maria@gmail.com     Madrid  123-456-789   
1     Luis    22      Medicina      luis@yahoo.es  Barcelona  987-654-321   
2   Carmen    20  Arquitectura   carmen@gmail.com    Sevilla  555-123-456   
3  Antonio    21      Economía  antonio@gmail.com   Valencia  789-321-654   
4     Sara    25    Psicología     sara@gmail.com   Zaragoza  111-222-333   
5    Pedro    30    Ingeniería     pedro@yahoo.es     Málaga  444-555-666   
6    Laura    28       Derecho    laura@gmail.com     Murcia  777-888-999   

      genero  hobbies nacionalidad idioma_principal  puntuacion_examen  \
0   Femenino     Leer     Española          Español                 85   
1  Masculino  Deporte     Mexicana          Español                 92   
2   Femenino     Arte     Española          Español                 78   
3  Masculino   Viajar   Colombiana          Español                 88   
4   Femenino   Música      Chilena          Español                 95   
5  Masculino     Cine      Peruana          Español                 86   
6   Femenino   Cocina    Argentina          Español                 90   

  estado_civil nivel_educativo  altura   peso  
0      Soltera    Licenciatura  180.43  63.33  
1      Soltero    Licenciatura  184.36  82.26  
2      Soltera    Licenciatura  176.32  56.45  
3      Soltero    Licenciatura  159.25  58.06  
4       Casada        Maestría  170.33  90.22  
5      Soltero    Licenciatura  170.99  84.68  
6       Casada       Doctorado  168.37  67.17

**Obtener la información del DataFrame**

In [21]:
tabla.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   nombre             20 non-null     object 
 1   edad               20 non-null     int64  
 2   grado              20 non-null     object 
 3   correo             20 non-null     object 
 4   ciudad             20 non-null     object 
 5   telefono           20 non-null     object 
 6   genero             20 non-null     object 
 7   hobbies            20 non-null     object 
 8   nacionalidad       20 non-null     object 
 9   idioma_principal   20 non-null     object 
 10  puntuacion_examen  20 non-null     int64  
 11  estado_civil       20 non-null     object 
 12  nivel_educativo    20 non-null     object 
 13  altura             20 non-null     float64
 14  peso               20 non-null     float64
dtypes: float64(2), int64(2), object(11)
memory usage: 2.5+ KB


**Desplegar un análisis estadístico descriptivo de las variables numéricas**

In [22]:
tabla.describe()

edad  puntuacion_examen      altura       peso
count  20.000000          20.000000   20.000000  20.000000
mean   28.850000          88.250000  170.020000  76.333500
std     6.579674           5.757147   11.020296  17.188162
min    18.000000          78.000000  150.720000  50.760000
25%    23.750000          84.750000  161.827500  61.382500
50%    28.500000          88.500000  170.200000  77.550000
75%    33.500000          92.250000  178.510000  92.170000
max    40.000000          97.000000  187.940000  98.840000

**Obtener las dimensiones del dataframe, y con esta función hacer un ```print(f"")```indicando la cantidad de filas y columnas...**

Pista: usar ```shape```

In [29]:
filas, columnas=tabla.shape

print(f"El dataframe tiene {filas} filas y {columnas} columnas que lo componen")

El dataframe tiene 20 filas y 15 columnas que lo componen


**Realiza un filtro que separe a los alumnos con calificación mayor a 90 y guarda los datos en un nuevo DataFrame llamado "Prom_Altos"**

In [32]:

Prom_Altos = tabla[tabla['puntuacion_examen'] > 90]

# Imprimir el nuevo DataFrame
print("DataFrame 'Prom_Altos':")
print(Prom_Altos)


DataFrame 'Prom_Altos':
       nombre  edad               grado               correo  \
1        Luis    22            Medicina        luis@yahoo.es   
4        Sara    25          Psicología       sara@gmail.com   
9      Carlos    26         Informática     carlos@gmail.com   
11      Pablo    27              Física       pablo@yahoo.es   
14    Natalia    35  Ciencias Políticas     natalia@yahoo.es   
16      Lucía    40          Psicología      lucia@gmail.com   
17     Miguel    38          Ingeniería      miguel@yahoo.es   
19  Francisco    39           Marketing  francisco@gmail.com   

                    ciudad     telefono     genero     hobbies  \
1                Barcelona  987-654-321  Masculino     Deporte   
4                 Zaragoza  111-222-333   Femenino      Música   
9                 Zaragoza  888-999-000  Masculino  Senderismo   
11                   Gijón  444-555-666  Masculino      Bailar   
14                 Granada  555-666-777   Femenino   Bicicleta   
16 

**Sobre el DataFrame original, crea una nueva columna, que divida la puntuación del examen sobre 10, el nombre de esta columna será ```Calificación```, y despliega el DataFrame**

In [33]:

tabla['Calificación'] = tabla['puntuacion_examen'] / 10

print("DataFrame con la nueva columna 'Calificación':")
print(tabla)


DataFrame con la nueva columna 'Calificación':
       nombre  edad               grado               correo  \
0       María    18            Economía      maria@gmail.com   
1        Luis    22            Medicina        luis@yahoo.es   
2      Carmen    20        Arquitectura     carmen@gmail.com   
3     Antonio    21            Economía    antonio@gmail.com   
4        Sara    25          Psicología       sara@gmail.com   
5       Pedro    30          Ingeniería       pedro@yahoo.es   
6       Laura    28             Derecho      laura@gmail.com   
7      Javier    23           Marketing     javier@gmail.com   
8         Ana    29            Biología         ana@yahoo.es   
9      Carlos    26         Informática     carlos@gmail.com   
10      Elena    24          Periodismo      elena@gmail.com   
11      Pablo    27              Física       pablo@yahoo.es   
12     Isabel    32            Historia     isabel@gmail.com   
13       Juan    31         Matemáticas       juan@gmail.

**Una vez creada la nueva columna, elimina la columna ```puntuacion_examen```, y despliega el DataFrame**

In [34]:

tabla = tabla.drop('puntuacion_examen', axis=1)

print("DataFrame con la columna 'puntuacion_examen' eliminada:")
print(tabla)


DataFrame con la columna 'puntuacion_examen' eliminada:
       nombre  edad               grado               correo  \
0       María    18            Economía      maria@gmail.com   
1        Luis    22            Medicina        luis@yahoo.es   
2      Carmen    20        Arquitectura     carmen@gmail.com   
3     Antonio    21            Economía    antonio@gmail.com   
4        Sara    25          Psicología       sara@gmail.com   
5       Pedro    30          Ingeniería       pedro@yahoo.es   
6       Laura    28             Derecho      laura@gmail.com   
7      Javier    23           Marketing     javier@gmail.com   
8         Ana    29            Biología         ana@yahoo.es   
9      Carlos    26         Informática     carlos@gmail.com   
10      Elena    24          Periodismo      elena@gmail.com   
11      Pablo    27              Física       pablo@yahoo.es   
12     Isabel    32            Historia     isabel@gmail.com   
13       Juan    31         Matemáticas       ju